modLoader = "kotlinforforge"
loaderVersion = "[3.9,)"
license = 'https://github.com/PssbleTrngle/${repository}/blob/1.19.x/LICENSE.txt'
issueTrackerURL = "https://github.com/PssbleTrngle/${repository}/issues"
showAsResourcePack = false

[[mods]]
    modId = "${mod_id}"
    version = "${mod_version}"
    displayName = "${mod_name}"
    authors = "${mod_author}"
    description = '''Skygrid'''
    credits = "Sethbling for the original idea"

[[dependencies.${mod_id}]]
    modId = "forge"
    mandatory = true
    versionRange = "[43,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19.2,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId="kotlinforforge"
    mandatory=true
    versionRange="[3.9.1,)"
    ordering="NONE"
    side="BOTH"
