# Make sure this is set to "kotlinforforge"
modLoader = "kotlinforforge"
# Make sure this is set to the appropriate version range
loaderVersion = "[2.2,)" # Require at least 2.0.x
# License is REQUIRED after 1.16
license = 'LGPL'

[[mods]]
modId = "skygrid"
version = "${file.jarVersion}"
displayName = "Skygrid"
authors = "possible_triangle"
description = '''Skygrid the people'''

[[dependencies.skygrid]]
modId = "forge"
mandatory = true
versionRange = "[38,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.skygrid]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.1]"
ordering = "NONE"
side = "BOTH"
