name: Deploy Website
on:
  workflow_dispatch:
  push:
    branches: [1.18.x]
    paths: [web/**]

jobs:
  generate:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - run: yarn install --frozen-lockfile
        working-directory: datagen

      - name: Generate Data & Assets
        run: yarn generate --from sources.json --data generated/data --icons generated/public/blocks --lang generated/lang
        working-directory: datagen
        env:
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_DOWNLOAD_TOKEN }}
          VANILLA_DATA: ${{ secrets.VANILLA_DATA }}

      - uses: actions/upload-artifact@v3
        with:
          name: data
          path: datagen/generated
          retention-days: 1

  deploy:
    needs: generate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v3
        with:
          name: data
          path: web

      - name: Build & Publish Container
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          image_name: ${{ secrets.DOCKER_USERNAME }}/skygrid-web
          context: web
